version: '3.2'

services:
  idioms_container:
    build: 
      context: .
      dockerfile: Dockerfile-cpu
    ports:
      - 80:80
    restart: "no"
    volumes:
      - ./models/xlm-roberta-base-pie:/var/model