version: '3.2'

services:
  fastapi:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    restart: "no"
    environment:
        - MODEL_PATH=${MODEL_PATH}
    volumes:
      - ${MODEL_PATH:-./placeholder_path}:/var/model
    healthcheck:
      # If the command returns 2, docker takes it as an undefined behaviour => 'exit 1'
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  streamlit:
    build: 
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    depends_on:
      fastapi:
        condition: service_healthy

networks:
  deploy_network:
    driver: bridge
