FROM python:3.8-slim-buster

WORKDIR /code
COPY requirements-api-cpu.txt /code/requirements.txt

RUN python -m venv /venv && \
    . /venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /code/requirements.txt

COPY . /code/api
CMD ["/venv/bin/python", "-m", "uvicorn", "api.server:app", "--host", "0.0.0.0", "--port", "80"]